trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UseNode@1
    inputs:
      version: "20.x"

  - script: |
      node --version
      npm --version
    displayName: "Check Node.js and npm versions"
